### ISSUE TITLE
[BUG] ImportError: cannot import name 'etree' from 'markdown.util'

### ISSUE THREAD

**Issue by emign** [Mara-Li/mkdocs_embed_file_plugins#1]
Crossreferencing this issue : https://github.com/neurobin/mdx_wikilink_plus/issues/10 , because it concerns this plugin as well.

**Comment by Mara-Li** [comment]
The strange things : i created a fork of mdx wikilink, changed the error line, but in github actions it continues to take the original mdx...
Normally. The problem must be fixed by the uses of the fork, as it works in local.

**Comment by emign** [comment]
How can I use the fork as library for ezlinks and embed_file? Because they import mdx_wikilink_plus as transient dependency
